
# /Users/shen/PycharmProjects/math_equation_typeset/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8FF5F464321B2DCEF20182EE49B1FE5E'
    
_lr_action_items = {'$end':([1,23,],[0,-1,]),'INT':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[5,-12,5,5,-10,-11,-9,5,5,-13,5,5,5,5,5,-5,-6,5,5,5,-4,-7,-8,]),'LSETBRACKET':([5,7,18,19,26,27,28,39,40,41,],[13,15,24,25,31,32,33,42,43,44,]),'UNDERSCORE':([4,9,11,12,22,],[-12,-10,-11,19,-13,]),'SUM':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[7,-12,7,7,-10,-11,-9,7,7,-13,7,7,7,7,7,-5,-6,7,7,7,-4,-7,-8,]),'LPAREN':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[8,-12,8,8,-10,-11,-9,8,8,-13,8,8,8,8,8,-5,-6,8,8,8,-4,-7,-8,]),'DOLLAR':([0,2,4,6,9,10,11,12,14,17,22,34,35,48,49,50,],[2,3,-12,-3,-10,17,-11,-9,-2,23,-13,-5,-6,-4,-7,-8,]),'NAME':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[9,-12,9,9,-10,-11,-9,9,9,-13,9,9,9,9,9,-5,-6,9,9,9,-4,-7,-8,]),'CONJUNCTION':([4,9,11,12,19,22,],[-12,-10,-11,18,26,-13,]),'SPACE':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[4,-12,4,4,-10,-11,-9,4,4,-13,4,4,4,4,4,-5,-6,4,4,4,-4,-7,-8,]),'NUMBER':([3,4,6,8,9,11,12,13,15,22,24,25,31,32,33,34,35,42,43,44,48,49,50,],[11,-12,11,11,-10,-11,-9,11,11,-13,11,11,11,11,11,-5,-6,11,11,11,-4,-7,-8,]),'RPAREN':([4,6,9,11,12,14,16,22,34,35,48,49,50,],[-12,-3,-10,-11,-9,-2,22,-13,-5,-6,-4,-7,-8,]),'RSETBRACKET':([4,6,9,11,12,14,20,21,22,29,30,34,35,36,37,38,45,46,47,48,49,50,],[-12,-3,-10,-11,-9,-2,27,28,-13,34,35,-5,-6,39,40,41,48,49,50,-4,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'t':([3,6,8,13,15,24,25,31,32,33,42,43,44,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'b':([3,6,8,13,15,24,25,31,32,33,42,43,44,],[10,14,16,20,21,29,30,36,37,38,45,46,47,]),'s':([0,],[1,]),'r':([3,6,8,13,15,24,25,31,32,33,42,43,44,],[12,12,12,12,12,12,12,12,12,12,12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> s","S'",1,None,None,None),
  ('s -> DOLLAR DOLLAR b DOLLAR DOLLAR','s',5,'p_s_b','equation.py',74),
  ('b -> t b','b',2,'p_b_tb','equation.py',79),
  ('b -> t','b',1,'p_b_tb','equation.py',80),
  ('t -> r UNDERSCORE CONJUNCTION LSETBRACKET b RSETBRACKET LSETBRACKET b RSETBRACKET','t',9,'p_b_up_down','equation.py',85),
  ('t -> r CONJUNCTION LSETBRACKET b RSETBRACKET','t',5,'p_t_up','equation.py',90),
  ('t -> r UNDERSCORE LSETBRACKET b RSETBRACKET','t',5,'p_b_down','equation.py',95),
  ('t -> INT LSETBRACKET b RSETBRACKET LSETBRACKET b RSETBRACKET LSETBRACKET b RSETBRACKET','t',10,'p_b_int','equation.py',100),
  ('t -> SUM LSETBRACKET b RSETBRACKET LSETBRACKET b RSETBRACKET LSETBRACKET b RSETBRACKET','t',10,'p_b_sum','equation.py',105),
  ('t -> r','t',1,'p_r_','equation.py',110),
  ('r -> NAME','r',1,'p_b_something','equation.py',115),
  ('r -> NUMBER','r',1,'p_b_something','equation.py',116),
  ('r -> SPACE','r',1,'p_b_something','equation.py',117),
  ('r -> LPAREN b RPAREN','r',3,'p_b_something','equation.py',118),
]
